import React, { ReactElement, useState } from 'react'
import {
  Image,
  StyleSheet,
  View,
  TouchableOpacity,
} from 'react-native'
import { IClientMeta } from '@walletconnect/types'

import images from 'assets/images'
import { Button, Icon, Text } from 'components'
import { StackScreenProps } from '@react-navigation/stack'
import { RootStackParams } from 'types'
import color from 'styles/color'
import { UTIL } from 'consts'

type Props = StackScreenProps<RootStackParams, 'WalletConnectConfirm'>

const Details = ({ route }: Props): ReactElement => {
  const params = UTIL.jsonTryStringify(route.params, null, 2)
  const [isOpen, setIsOpen] = useState(false)
  return (
    <View style={styles.openBox}>
      <View
        style={{
          flexDirection: 'row',
          justifyContent: 'space-between',
        }}
      >
        <View
          style={{
            borderRadius: 5,
            backgroundColor: color.red,
            paddingHorizontal: 5,
          }}
        >
          <Text style={styles.executeContract} fontType="bold">
            Details
          </Text>
        </View>
        <TouchableOpacity
          style={styles.openBtn}
          onPress={(): void => {
            setIsOpen(!isOpen)
          }}
        >
          <Text
            style={{ color: color.dodgerBlue, fontSize: 10 }}
            fontType="bold"
          >
            {isOpen ? 'Collapse' : 'Expand'}
          </Text>
          <Icon
            name={isOpen ? 'expand-less' : 'expand-more'}
            size={14}
            color={color.dodgerBlue}
          />
        </TouchableOpacity>
      </View>
      {isOpen && (
        <View style={{ paddingTop: 15 }}>
          <Text>{params}</Text>
        </View>
      )}
    </View>
  )
}

const ErrorBox = ({
  peerMeta,
  denySign,
  onPressGoBack,
  route,
  navigation,
}: {
  peerMeta: IClientMeta | null
  denySign: () => void
  onPressGoBack: () => void
} & Props): ReactElement => {
  return (
    <>
      <View style={{ alignItems: 'center', paddingTop: 40 }}>
        <Image
          source={images.oops_face}
          style={{ width: 60, height: 60 }}
        />
        <Text style={styles.errorTitle} fontType="bold">
          Invalid Transaction Request
        </Text>
        <Text
          style={{
            fontSize: 16,
            fontStyle: 'normal',
            lineHeight: 24,
            letterSpacing: 0,
            textAlign: 'center',
          }}
        >
          {peerMeta ? `origin : ${peerMeta.name}\n` : ''}
          {
            'This usually occurs when a transaction generated by the app does not match the protocol.\nPlease contact origin administrator.'
          }
        </Text>
        <Details {...{ route, navigation }} />
      </View>
      <Button
        theme={'red'}
        title={'Continue'}
        onPress={(): void => {
          denySign()
          onPressGoBack()
        }}
        containerStyle={{
          marginTop: 20,
          marginBottom: 40,
        }}
      />
    </>
  )
}

export default ErrorBox

const styles = StyleSheet.create({
  openBox: {
    width: '100%',
    paddingVertical: 15,
    paddingHorizontal: 15,
    marginTop: 50,
    marginBottom: 20,
    borderRadius: 5,
    backgroundColor: '#ffffff',
    shadowColor: 'rgba(0, 0, 0, 0.05)',
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowRadius: 10,
    shadowOpacity: 1,
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#ebeff8',
  },
  executeContract: {
    fontSize: 12,
    fontStyle: 'normal',
    lineHeight: 21,
    letterSpacing: 0,
    color: '#ffffff',
  },
  openBtn: {
    borderRadius: 3,
    borderWidth: 1,
    borderColor: color.dodgerBlue,
    paddingHorizontal: 10,
    paddingVertical: 3,
    marginRight: 5,
    flexDirection: 'row',
    alignItems: 'center',
  },
  errorTitle: {
    fontSize: 20,
    lineHeight: 36,
    letterSpacing: 0,
    textAlign: 'center',
  },
})
