platform :ios, '11.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

target 'TerraStation' do
  use_unimodules!(exclude: [
    'expo-file-system',
    'unimodules-file-system-interface',
  ])

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID"

  pod 'TrezorCrypto'
  #pod 'IOSSecuritySuite'
  pod 'IOSSecuritySuite', :git => 'https://github.com/bokuhe/IOSSecuritySuite.git', :branch => 'feat/ios-app-on-mac'

  config = use_native_modules!
  use_react_native!(
    :path => config["reactNativePath"],
    :hermes_enabled => true
  )




  target 'TerraStationTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!('Flipper' => '0.87.0', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1')

  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '-DDONT_AUTOINSTALL_REANIMATED'
      end
    end
  end
end

