export default {
  on_boarding_0: require('../../assets/on_boarding_0.png'),
  on_boarding_1: require('../../assets/on_boarding_1.png'),
  on_boarding_2: require('../../assets/on_boarding_2.png'),
  on_boarding_3: require('../../assets/on_boarding_3.png'),
  on_boarding_4: require('../../assets/on_boarding_4.png'),
  terra: require('../../assets/terra.png'),
  satelite: require('../../assets/satelite.png'),
  bio_face: require('../../assets/bio_face.png'),
  finger_print: require('../../assets/finger_print.png'),
  loading_image: require('../../assets/loading_image.gif'),
  take_qrcode: require('../../assets/take_qrcode.png'),
  loading_circle: require('../../assets/loading_circle.gif'),
  walletconnect_blue: require('../../assets/walletconnect_blue.png'),
  walletconnect_white: require('../../assets/walletconnect_white.png'),
  wallet_settings: require('../../assets/wallet_settings.png'),
  oops_face: require('../../assets/oops_face.png'),
  queued: require('../../assets/queued.png'),
}
